const fs = require('fs-extra');
const path = require('path');
const os = require('os');

const AiderIntegration = require('../../lib/integrations/aider-integration');

describe('AiderIntegration', () => {
  let tempDir;
  let originalCwd;

  beforeEach(async () => {
    tempDir = await fs.mkdtemp(path.join(os.tmpdir(), 'contextkit-aider-'));
    originalCwd = process.cwd();
    process.chdir(tempDir);
  });

  afterEach(async () => {
    process.chdir(originalCwd);
    await fs.remove(tempDir);
  });

  test('1. creates CONVENTIONS.md bridge file', async () => {
    const integration = new AiderIntegration();
    await integration.install();

    expect(await fs.pathExists('CONVENTIONS.md')).toBe(true);
    const content = await fs.readFile('CONVENTIONS.md', 'utf-8');
    expect(content).toContain('<!-- Generated by ContextKit -->');
    expect(content).toContain('.contextkit/standards/code-style.md');
  });

  test('2. creates .aider/rules.md', async () => {
    const integration = new AiderIntegration();
    await integration.install();

    expect(await fs.pathExists('.aider/rules.md')).toBe(true);
    const content = await fs.readFile('.aider/rules.md', 'utf-8');
    expect(content).toContain('contextkit');
  });

  test('3. creates .aiderignore when it does not exist', async () => {
    const integration = new AiderIntegration();
    await integration.install();

    expect(await fs.pathExists('.aiderignore')).toBe(true);
    const content = await fs.readFile('.aiderignore', 'utf-8');
    expect(content).toContain('.contextkit/hooks/');
  });

  test('4. does not overwrite existing .aiderignore', async () => {
    await fs.writeFile('.aiderignore', 'my-custom-ignore\n');

    const integration = new AiderIntegration();
    await integration.install();

    const content = await fs.readFile('.aiderignore', 'utf-8');
    expect(content).toBe('my-custom-ignore\n');
  });

  test('5. appends to existing CONVENTIONS.md without overwriting', async () => {
    await fs.writeFile('CONVENTIONS.md', '# My Conventions\n\nCustom content.\n');

    const integration = new AiderIntegration();
    await integration.install();

    const content = await fs.readFile('CONVENTIONS.md', 'utf-8');
    expect(content).toContain('# My Conventions');
    expect(content).toContain('Custom content.');
    expect(content).toContain('<!-- Generated by ContextKit -->');
  });

  test('6. validate returns valid after install', async () => {
    const integration = new AiderIntegration();
    await integration.install();

    const result = await integration.validate();
    expect(result.valid).toBe(true);
    expect(result.present).toContain('CONVENTIONS.md');
    expect(result.present).toContain('.aider/rules.md');
  });
});
