const fs = require('fs-extra');
const path = require('path');
const os = require('os');

const BaseIntegration = require('../../lib/integrations/base-integration');

// Concrete subclass for testing
class TestIntegration extends BaseIntegration {
  constructor() {
    super();
    this.name = 'test';
    this.displayName = 'Test Platform';
    this.generatedFiles = ['test-generated.md'];
    this.bridgeFiles = ['TEST_BRIDGE.md'];
    this.platformDir = '.test-platform';
  }

  async generateFiles() {
    await this.writeGeneratedFile('test-generated.md', '# Generated');
    await this.writeBridgeFile('TEST_BRIDGE.md', '# Bridge Content');
  }
}

describe('BaseIntegration', () => {
  let tempDir;
  let originalCwd;

  beforeEach(async () => {
    tempDir = await fs.mkdtemp(path.join(os.tmpdir(), 'vibe-kit-test-'));
    originalCwd = process.cwd();
    process.chdir(tempDir);
  });

  afterEach(async () => {
    process.chdir(originalCwd);
    await fs.remove(tempDir);
  });

  test('1. cannot instantiate BaseIntegration directly', () => {
    expect(() => new BaseIntegration()).toThrow('abstract');
  });

  test('2. install creates platform directory and calls generateFiles', async () => {
    const integration = new TestIntegration();
    await integration.install();

    expect(await fs.pathExists('.test-platform')).toBe(true);
    expect(await fs.pathExists('test-generated.md')).toBe(true);
    expect(await fs.pathExists('TEST_BRIDGE.md')).toBe(true);
  });

  test('3. validate returns valid when all files exist', async () => {
    const integration = new TestIntegration();
    await integration.install();

    const result = await integration.validate();
    expect(result.valid).toBe(true);
    expect(result.present).toContain('test-generated.md');
    expect(result.present).toContain('TEST_BRIDGE.md');
    expect(result.missing).toHaveLength(0);
  });

  test('4. validate returns invalid when files are missing', async () => {
    const integration = new TestIntegration();
    const result = await integration.validate();

    expect(result.valid).toBe(false);
    expect(result.missing).toContain('test-generated.md');
    expect(result.missing).toContain('TEST_BRIDGE.md');
  });

  test('5. writeBridgeFile creates new file with markers', async () => {
    const integration = new TestIntegration();
    await integration.writeBridgeFile('bridge.md', 'Hello World');

    const content = await fs.readFile('bridge.md', 'utf-8');
    expect(content).toContain('<!-- Generated by Vibe Kit -->');
    expect(content).toContain('Hello World');
    expect(content).toContain('<!-- End Vibe Kit -->');
  });

  test('6. writeBridgeFile replaces marked section in existing file', async () => {
    const integration = new TestIntegration();

    // Create initial file with markers
    await integration.writeBridgeFile('bridge.md', 'Version 1');
    // Replace with new content
    await integration.writeBridgeFile('bridge.md', 'Version 2');

    const content = await fs.readFile('bridge.md', 'utf-8');
    expect(content).toContain('Version 2');
    expect(content).not.toContain('Version 1');
    // Should only have one set of markers
    expect(content.split('<!-- Generated by Vibe Kit -->').length).toBe(2);
  });

  test('7. writeBridgeFile appends to existing file without markers', async () => {
    const integration = new TestIntegration();

    // Create manual file without markers
    await fs.writeFile('bridge.md', '# My Custom Content\n\nThis is user content.\n');
    // Append vibe-kit section
    await integration.writeBridgeFile('bridge.md', 'Vibe Kit Section');

    const content = await fs.readFile('bridge.md', 'utf-8');
    expect(content).toContain('# My Custom Content');
    expect(content).toContain('This is user content.');
    expect(content).toContain('Vibe Kit Section');
    expect(content).toContain('<!-- Generated by Vibe Kit -->');
  });

  test('8. getStandardsBlock returns standards reference markdown', () => {
    const integration = new TestIntegration();
    const block = integration.getStandardsBlock();

    expect(block).toContain('.vibe-kit/standards/code-style.md');
    expect(block).toContain('.vibe-kit/standards/testing.md');
    expect(block).toContain('.vibe-kit/standards/architecture.md');
    expect(block).toContain('.vibe-kit/commands/analyze.md');
    expect(block).toContain('.vibe-kit/product/mission-lite.md');
  });
});
