const fs = require('fs-extra');
const path = require('path');
const os = require('os');

const ClaudeIntegration = require('../../lib/integrations/claude-integration');

describe('ClaudeIntegration', () => {
  let tempDir;
  let originalCwd;

  beforeEach(async () => {
    tempDir = await fs.mkdtemp(path.join(os.tmpdir(), 'contextkit-claude-'));
    originalCwd = process.cwd();
    process.chdir(tempDir);
  });

  afterEach(async () => {
    process.chdir(originalCwd);
    await fs.remove(tempDir);
  });

  test('1. creates CLAUDE.md bridge file', async () => {
    const integration = new ClaudeIntegration();
    await integration.install();

    expect(await fs.pathExists('CLAUDE.md')).toBe(true);
    const content = await fs.readFile('CLAUDE.md', 'utf-8');
    expect(content).toContain('<!-- Generated by ContextKit -->');
    expect(content).toContain('Project Standards');
    expect(content).toContain('.contextkit/standards/code-style.md');
  });

  test('2. creates .claude/rules/contextkit-standards.md with alwaysApply', async () => {
    const integration = new ClaudeIntegration();
    await integration.install();

    const filePath = '.claude/rules/contextkit-standards.md';
    expect(await fs.pathExists(filePath)).toBe(true);
    const content = await fs.readFile(filePath, 'utf-8');
    expect(content).toContain('alwaysApply: true');
    expect(content).toContain('auto-loaded via CLAUDE.md imports');
    expect(content).toContain('Code style conventions (from code-style.md)');
  });

  test('3. creates .claude/rules/contextkit-testing.md with test file globs', async () => {
    const integration = new ClaudeIntegration();
    await integration.install();

    const filePath = '.claude/rules/contextkit-testing.md';
    expect(await fs.pathExists(filePath)).toBe(true);
    const content = await fs.readFile(filePath, 'utf-8');
    expect(content).toContain('**/*.test.*');
    expect(content).toContain('**/*.spec.*');
    expect(content).toContain('numbered');
  });

  test('4. creates .claude/rules/contextkit-code-style.md with source globs', async () => {
    const integration = new ClaudeIntegration();
    await integration.install();

    const filePath = '.claude/rules/contextkit-code-style.md';
    expect(await fs.pathExists(filePath)).toBe(true);
    const content = await fs.readFile(filePath, 'utf-8');
    expect(content).toContain('src/**');
    expect(content).toContain('lib/**');
  });

  test('5. creates all slash command files', async () => {
    const integration = new ClaudeIntegration();
    await integration.install();

    const commands = [
      'analyze', 'review', 'fix', 'refactor', 'test', 'doc',
      'squad', 'squad-architect', 'squad-dev', 'squad-test', 'squad-review',
      'squad-batch', 'squad-run',
    ];
    for (const cmd of commands) {
      const filePath = `.claude/commands/${cmd}.md`;
      expect(await fs.pathExists(filePath)).toBe(true);
      const content = await fs.readFile(filePath, 'utf-8');
      expect(content).toContain('.contextkit/commands/');
    }
  });

  test('6. appends to existing CLAUDE.md without overwriting', async () => {
    // Create a manual CLAUDE.md
    await fs.writeFile('CLAUDE.md', '# My Custom Claude Config\n\nCustom rules here.\n');

    const integration = new ClaudeIntegration();
    await integration.install();

    const content = await fs.readFile('CLAUDE.md', 'utf-8');
    expect(content).toContain('# My Custom Claude Config');
    expect(content).toContain('Custom rules here.');
    expect(content).toContain('<!-- Generated by ContextKit -->');
    expect(content).toContain('.contextkit/standards/code-style.md');
  });

  test('7. validate returns valid after install', async () => {
    const integration = new ClaudeIntegration();
    await integration.install();

    const result = await integration.validate();
    expect(result.valid).toBe(true);
    expect(result.missing).toHaveLength(0);
  });

  test('8. validate returns invalid before install', async () => {
    const integration = new ClaudeIntegration();
    const result = await integration.validate();

    expect(result.valid).toBe(false);
    expect(result.missing.length).toBeGreaterThan(0);
  });
});
