const fs = require('fs-extra');
const path = require('path');
const os = require('os');

const ClaudeIntegration = require('../../lib/integrations/claude-integration');

describe('ClaudeIntegration', () => {
  let tempDir;
  let originalCwd;

  beforeEach(async () => {
    tempDir = await fs.mkdtemp(path.join(os.tmpdir(), 'vibe-kit-claude-'));
    originalCwd = process.cwd();
    process.chdir(tempDir);
  });

  afterEach(async () => {
    process.chdir(originalCwd);
    await fs.remove(tempDir);
  });

  test('1. creates CLAUDE.md bridge file', async () => {
    const integration = new ClaudeIntegration();
    await integration.install();

    expect(await fs.pathExists('CLAUDE.md')).toBe(true);
    const content = await fs.readFile('CLAUDE.md', 'utf-8');
    expect(content).toContain('<!-- Generated by Vibe Kit -->');
    expect(content).toContain('Project Standards');
    expect(content).toContain('.vibe-kit/standards/code-style.md');
  });

  test('2. creates .claude/rules/vibe-kit-standards.md with alwaysApply', async () => {
    const integration = new ClaudeIntegration();
    await integration.install();

    const filePath = '.claude/rules/vibe-kit-standards.md';
    expect(await fs.pathExists(filePath)).toBe(true);
    const content = await fs.readFile(filePath, 'utf-8');
    expect(content).toContain('alwaysApply: true');
    expect(content).toContain('.vibe-kit/standards/code-style.md');
  });

  test('3. creates .claude/rules/vibe-kit-testing.md with test file globs', async () => {
    const integration = new ClaudeIntegration();
    await integration.install();

    const filePath = '.claude/rules/vibe-kit-testing.md';
    expect(await fs.pathExists(filePath)).toBe(true);
    const content = await fs.readFile(filePath, 'utf-8');
    expect(content).toContain('**/*.test.*');
    expect(content).toContain('**/*.spec.*');
    expect(content).toContain('numbered');
  });

  test('4. creates .claude/rules/vibe-kit-code-style.md with source globs', async () => {
    const integration = new ClaudeIntegration();
    await integration.install();

    const filePath = '.claude/rules/vibe-kit-code-style.md';
    expect(await fs.pathExists(filePath)).toBe(true);
    const content = await fs.readFile(filePath, 'utf-8');
    expect(content).toContain('src/**');
    expect(content).toContain('lib/**');
  });

  test('5. creates .claude/commands/analyze.md', async () => {
    const integration = new ClaudeIntegration();
    await integration.install();

    const filePath = '.claude/commands/analyze.md';
    expect(await fs.pathExists(filePath)).toBe(true);
    const content = await fs.readFile(filePath, 'utf-8');
    expect(content).toContain('analyze');
  });

  test('6. appends to existing CLAUDE.md without overwriting', async () => {
    // Create a manual CLAUDE.md
    await fs.writeFile('CLAUDE.md', '# My Custom Claude Config\n\nCustom rules here.\n');

    const integration = new ClaudeIntegration();
    await integration.install();

    const content = await fs.readFile('CLAUDE.md', 'utf-8');
    expect(content).toContain('# My Custom Claude Config');
    expect(content).toContain('Custom rules here.');
    expect(content).toContain('<!-- Generated by Vibe Kit -->');
    expect(content).toContain('.vibe-kit/standards/code-style.md');
  });

  test('7. validate returns valid after install', async () => {
    const integration = new ClaudeIntegration();
    await integration.install();

    const result = await integration.validate();
    expect(result.valid).toBe(true);
    expect(result.missing).toHaveLength(0);
  });

  test('8. validate returns invalid before install', async () => {
    const integration = new ClaudeIntegration();
    const result = await integration.validate();

    expect(result.valid).toBe(false);
    expect(result.missing.length).toBeGreaterThan(0);
  });
});
