const fs = require('fs-extra');
const path = require('path');
const os = require('os');

const CodexIntegration = require('../../lib/integrations/codex-integration');

describe('CodexIntegration', () => {
  let tempDir;
  let originalCwd;

  beforeEach(async () => {
    tempDir = await fs.mkdtemp(path.join(os.tmpdir(), 'contextkit-codex-'));
    originalCwd = process.cwd();
    process.chdir(tempDir);
  });

  afterEach(async () => {
    process.chdir(originalCwd);
    await fs.remove(tempDir);
  });

  test('1. creates AGENTS.md bridge file', async () => {
    const integration = new CodexIntegration();
    await integration.install();

    expect(await fs.pathExists('AGENTS.md')).toBe(true);
    const content = await fs.readFile('AGENTS.md', 'utf-8');
    expect(content).toContain('<!-- Generated by ContextKit -->');
    expect(content).toContain('.contextkit/standards/code-style.md');
  });

  test('2. does not create .codex/ directory', async () => {
    const integration = new CodexIntegration();
    await integration.install();

    expect(await fs.pathExists('.codex')).toBe(false);
  });

  test('3. appends to existing AGENTS.md without overwriting', async () => {
    await fs.writeFile('AGENTS.md', '# My Agents Config\n\nCustom content.\n');

    const integration = new CodexIntegration();
    await integration.install();

    const content = await fs.readFile('AGENTS.md', 'utf-8');
    expect(content).toContain('# My Agents Config');
    expect(content).toContain('Custom content.');
    expect(content).toContain('<!-- Generated by ContextKit -->');
  });

  test('4. validate returns valid after install', async () => {
    const integration = new CodexIntegration();
    await integration.install();

    const result = await integration.validate();
    expect(result.valid).toBe(true);
    expect(result.present).toContain('AGENTS.md');
  });
});
