const fs = require('fs-extra');
const path = require('path');
const os = require('os');

const CopilotIntegration = require('../../lib/integrations/copilot-integration');

describe('CopilotIntegration', () => {
  let tempDir;
  let originalCwd;

  beforeEach(async () => {
    tempDir = await fs.mkdtemp(path.join(os.tmpdir(), 'contextkit-copilot-'));
    originalCwd = process.cwd();
    process.chdir(tempDir);
  });

  afterEach(async () => {
    process.chdir(originalCwd);
    await fs.remove(tempDir);
  });

  test('1. creates .github/copilot-instructions.md bridge file', async () => {
    const integration = new CopilotIntegration();
    await integration.install();

    expect(await fs.pathExists('.github/copilot-instructions.md')).toBe(true);
    const content = await fs.readFile('.github/copilot-instructions.md', 'utf-8');
    expect(content).toContain('<!-- Generated by ContextKit -->');
    expect(content).toContain('.contextkit/standards/code-style.md');
  });

  test('2. creates .vscode/settings.json with copilot config', async () => {
    const integration = new CopilotIntegration();
    await integration.install();

    expect(await fs.pathExists('.vscode/settings.json')).toBe(true);
    const settings = await fs.readJson('.vscode/settings.json');
    expect(settings['github.copilot.chat.codeGeneration.instructions']).toBeDefined();
    expect(settings['contextKit.standardsPath']).toBe('.contextkit/standards');
  });

  test('3. merges into existing .vscode/settings.json', async () => {
    await fs.ensureDir('.vscode');
    await fs.writeJson('.vscode/settings.json', { 'editor.fontSize': 14 });

    const integration = new CopilotIntegration();
    await integration.install();

    const settings = await fs.readJson('.vscode/settings.json');
    expect(settings['editor.fontSize']).toBe(14);
    expect(settings['github.copilot.chat.codeGeneration.instructions']).toBeDefined();
  });

  test('4. appends to existing .github/copilot-instructions.md', async () => {
    await fs.ensureDir('.github');
    await fs.writeFile('.github/copilot-instructions.md', '# My Custom Instructions\n\nDo this.\n');

    const integration = new CopilotIntegration();
    await integration.install();

    const content = await fs.readFile('.github/copilot-instructions.md', 'utf-8');
    expect(content).toContain('# My Custom Instructions');
    expect(content).toContain('Do this.');
    expect(content).toContain('<!-- Generated by ContextKit -->');
  });

  test('5. validate returns valid after install', async () => {
    const integration = new CopilotIntegration();
    await integration.install();

    const result = await integration.validate();
    expect(result.valid).toBe(true);
    expect(result.present).toContain('.github/copilot-instructions.md');
  });
});
