const fs = require('fs-extra');
const path = require('path');
const os = require('os');

const GeminiIntegration = require('../../lib/integrations/gemini-integration');

describe('GeminiIntegration', () => {
  let tempDir;
  let originalCwd;

  beforeEach(async () => {
    tempDir = await fs.mkdtemp(path.join(os.tmpdir(), 'contextkit-gemini-'));
    originalCwd = process.cwd();
    process.chdir(tempDir);
  });

  afterEach(async () => {
    process.chdir(originalCwd);
    await fs.remove(tempDir);
  });

  test('1. creates GEMINI.md bridge file', async () => {
    const integration = new GeminiIntegration();
    await integration.install();

    expect(await fs.pathExists('GEMINI.md')).toBe(true);
    const content = await fs.readFile('GEMINI.md', 'utf-8');
    expect(content).toContain('<!-- Generated by ContextKit -->');
    expect(content).toContain('.contextkit/standards/code-style.md');
  });

  test('2. creates .gemini/settings.json', async () => {
    const integration = new GeminiIntegration();
    await integration.install();

    expect(await fs.pathExists('.gemini/settings.json')).toBe(true);
    const settings = await fs.readJson('.gemini/settings.json');
    expect(settings.contextFiles).toContain('.contextkit/standards/code-style.md');
    expect(settings.contextFiles).toContain('.contextkit/standards/glossary.md');
  });

  test('3. appends to existing GEMINI.md without overwriting', async () => {
    await fs.writeFile('GEMINI.md', '# My Gemini Config\n\nCustom rules.\n');

    const integration = new GeminiIntegration();
    await integration.install();

    const content = await fs.readFile('GEMINI.md', 'utf-8');
    expect(content).toContain('# My Gemini Config');
    expect(content).toContain('Custom rules.');
    expect(content).toContain('<!-- Generated by ContextKit -->');
  });

  test('4. validate returns valid after install', async () => {
    const integration = new GeminiIntegration();
    await integration.install();

    const result = await integration.validate();
    expect(result.valid).toBe(true);
    expect(result.present).toContain('GEMINI.md');
    expect(result.present).toContain('.gemini/settings.json');
  });
});
