const fs = require('fs-extra');
const path = require('path');
const os = require('os');

const WindsurfIntegration = require('../../lib/integrations/windsurf-integration');

describe('WindsurfIntegration', () => {
  let tempDir;
  let originalCwd;

  beforeEach(async () => {
    tempDir = await fs.mkdtemp(path.join(os.tmpdir(), 'contextkit-windsurf-'));
    originalCwd = process.cwd();
    process.chdir(tempDir);
  });

  afterEach(async () => {
    process.chdir(originalCwd);
    await fs.remove(tempDir);
  });

  test('1. creates .windsurfrules bridge file', async () => {
    const integration = new WindsurfIntegration();
    await integration.install();

    expect(await fs.pathExists('.windsurfrules')).toBe(true);
    const content = await fs.readFile('.windsurfrules', 'utf-8');
    expect(content).toContain('<!-- Generated by ContextKit -->');
    expect(content).toContain('.contextkit/standards/code-style.md');
  });

  test('2. creates .windsurf/rules/contextkit-standards.md', async () => {
    const integration = new WindsurfIntegration();
    await integration.install();

    expect(await fs.pathExists('.windsurf/rules/contextkit-standards.md')).toBe(true);
    const content = await fs.readFile('.windsurf/rules/contextkit-standards.md', 'utf-8');
    expect(content).toContain('ContextKit Standards');
    expect(content).toContain('alwaysApply: true');
  });

  test('3. removes legacy vibe-kit-standards.md', async () => {
    await fs.ensureDir('.windsurf/rules');
    await fs.writeFile('.windsurf/rules/vibe-kit-standards.md', 'legacy');

    const integration = new WindsurfIntegration();
    await integration.install();

    expect(await fs.pathExists('.windsurf/rules/vibe-kit-standards.md')).toBe(false);
    expect(await fs.pathExists('.windsurf/rules/contextkit-standards.md')).toBe(true);
  });

  test('4. appends to existing .windsurfrules without overwriting', async () => {
    await fs.writeFile('.windsurfrules', '# My Windsurf Rules\n\nCustom content.\n');

    const integration = new WindsurfIntegration();
    await integration.install();

    const content = await fs.readFile('.windsurfrules', 'utf-8');
    expect(content).toContain('# My Windsurf Rules');
    expect(content).toContain('Custom content.');
    expect(content).toContain('<!-- Generated by ContextKit -->');
  });

  test('5. validate returns valid after install', async () => {
    const integration = new WindsurfIntegration();
    await integration.install();

    const result = await integration.validate();
    expect(result.valid).toBe(true);
    expect(result.present).toContain('.windsurfrules');
    expect(result.present).toContain('.windsurf/rules/contextkit-standards.md');
  });
});
